Repository 202303-PRM-TR-FEW/LearnU-Team-7, pull requests merged in 2023-07, with the labels that each got.

#15 add: custom blue background and text colors
  tailwind.config.js
Labels: enhancement

#16 add: get started button using LeanUButton
  app/Components/LearnUButton.jsx
  app/globals.css
  app/page.js
Labels: enhancement

#26 duplicated root page.jsx
  app/get-started/page.jsx
  app/page.js
Labels: bug

#17 Added IntroPic for first Step
  app/IntroPic.jsx
  app/styles/styles.css
Labels: enhancement

#29 Amdjed belgacem/issue5
  app/Components/IntroPic.jsx
  app/Components/SideBar.jsx
  app/get-started/page.jsx
  app/globals.css
  app/styles/styles.css
  dist/output.css
  next.config.js
  package-lock.json
  package.json
  tailwind.config.js
Labels: help wanted

#31 font family is defined
  app/globals.css
  app/layout.js
  package-lock.json
  tailwind.config.js
Labels: enhancement

#32 fix: intro page layout
  app/(content-pages)/home/page.jsx
  app/Components/IntroPic.jsx
  app/Components/TitleAndParagraph.jsx
  app/favicon.ico
  app/get-started/page.jsx
  app/layout.js
  public/intro.png
  tailwind.config.js
Labels: Fix

#34 fix: small padding bottom for text content
  app/get-started/page.jsx
Labels: Fix

#37 Home Page - Featured Courses
  app/(content-pages)/home/page.jsx
  app/(content-pages)/layout.jsx
  app/Components/FeaturedCourse.jsx
  app/Components/FeaturedCourses.jsx
  app/Components/LearnUButton.jsx
  app/Components/SaveIcon.jsx
  app/Components/SideBar.jsx
  app/Components/Tutor.jsx
  app/get-started/page.jsx
  app/globals.css
  next.config.js
  tailwind.config.js
Labels: enhancement

#50 SaveIcon hover effect and prop for svg fill property missing
  app/Components/SaveIcon.jsx
  package.json
Labels: Fix

#39 home page-categories component
  app/(content-pages)/home/page.jsx
  app/Components/Categories.jsx
  app/Components/Icons.jsx
  app/Components/SaveIcon.jsx
  app/Components/Tutor.jsx
  app/globals.css
Labels: feature

#53 Components-Group the Components
  app/(content-pages)/home/page.jsx
  app/(content-pages)/search/page.jsx
  app/Components/BrandIcon.jsx
  app/Components/FeaturedCourse.jsx
  app/Components/FeaturedCourses.jsx
  app/Components/GetStarted/BrandIcon.jsx
  app/Components/GetStarted/IntroPic.jsx
  app/Components/GetStarted/TitleAndParagraph.jsx
  app/Components/HomePage/Categories.jsx
  app/Components/HomePage/FeaturedCourse.jsx
  app/Components/HomePage/FeaturedCourses.jsx
  app/Components/HomePage/Tutor.jsx
  app/Components/Icons.jsx
  app/Components/SaveIcon.jsx
  app/Components/SearchPage/SearchFormPartTwo.jsx
  app/Components/SideBar.jsx
  app/get-started/page.jsx
Labels: Fix

#54 Translation of the Pages #46
  app/Components/GetStarted/TitleAndParagraph.jsx
  app/Components/HomePage/Categories.jsx
  app/Components/HomePage/FeaturedCourses.jsx
  app/Components/SideBar.jsx
  app/[locale]/(content-pages)/courses/[courseId]/page.jsx
  app/[locale]/(content-pages)/home/page.jsx
  app/[locale]/(content-pages)/layout.jsx
  app/[locale]/(content-pages)/my-learning/page.jsx
  app/[locale]/(content-pages)/profile/page.jsx
  app/[locale]/(content-pages)/saved/page.jsx
  app/[locale]/(content-pages)/search/page.jsx
  app/[locale]/(content-pages)/statistics/page.jsx
  app/[locale]/get-started/page.jsx
  app/[locale]/layout.jsx
  app/[locale]/page.jsx
  app/get-started/page.jsx
  app/page.jsx
  i18n.js
  messages/en.json
  messages/tr.json
  middleware.js
  next.config.js
  package-lock.json
  package.json
Labels: feature

#51 4Furki4/issue18
  __mocks__/fileMock.js
  __mocks__/styleMock.js
  app/Components/__tests__/LearnUButton.test.js
  jest.config.js
  package-lock.json
  package.json
Labels: feature

#59 Pluviophillee/issue43 - Search part one added
  app/Components/SearchPage/SearchFormPartOne.jsx
  app/[locale]/(content-pages)/search/page.jsx
  app/[locale]/layout.jsx
  messages/en.json
  messages/tr.json
  package-lock.json
Labels: enhancement

#41 Home page My Learning part design is added
  app/Components/MyLearning.jsx
Labels: enhancement

#60 Amdjed
  app/Components/CategoriesExpansion.jsx
  app/Components/HomePage/Categories.jsx
  app/Components/Icons.jsx
  app/Components/MyLearning.jsx
  app/Components/MyLearningCard.jsx
  app/Components/SideBar.jsx
  app/[locale]/(content-pages)/home/page.jsx
  app/[locale]/layout.jsx
  messages/en.json
  messages/tr.json
  public/turkey.png
  public/united-states-of-america.png
Labels: enhancement, Fix

#57 Search Form Part Two has been added
  app/Components/CategoriesArray.jsx
  app/Components/HomePage/Categories.jsx
  app/Components/Icons.jsx
  app/Components/SearchPage/SearchFormPartTwo.jsx
  app/[locale]/(content-pages)/search/page.jsx
  app/globals.css
  app/layout.js
  messages/en.json
  messages/tr.json
  package-lock.json
  package.json
Labels: feature

#68 Release 0.1
  __mocks__/fileMock.js
  __mocks__/styleMock.js
  app/Components/CategoriesArray.jsx
  app/Components/CategoriesExpansion.jsx
  app/Components/GetStarted/BrandIcon.jsx
  app/Components/GetStarted/IntroPic.jsx
  app/Components/GetStarted/TitleAndParagraph.jsx
  app/Components/HomePage/Categories.jsx
  app/Components/HomePage/FeaturedCourse.jsx
  app/Components/HomePage/FeaturedCourses.jsx
  app/Components/HomePage/Tutor.jsx
  app/Components/Icons.jsx
  app/Components/LearnUButton.jsx
  app/Components/MyLearning.jsx
  app/Components/MyLearningCard.jsx
  app/Components/SearchPage/SearchFormPartOne.jsx
  app/Components/SearchPage/SearchFormPartTwo.jsx
  app/Components/SideBar.jsx
  app/Components/__tests__/LearnUButton.test.js
  app/[locale]/(content-pages)/courses/[courseId]/page.jsx
  app/[locale]/(content-pages)/home/page.jsx
  app/[locale]/(content-pages)/layout.jsx
  app/[locale]/(content-pages)/my-learning/page.jsx
  app/[locale]/(content-pages)/profile/page.jsx
  app/[locale]/(content-pages)/saved/page.jsx
  app/[locale]/(content-pages)/search/page.jsx
  app/[locale]/(content-pages)/statistics/page.jsx
  app/[locale]/get-started/page.jsx
  app/[locale]/layout.jsx
  app/[locale]/page.jsx
  app/favicon.ico
  app/globals.css
  app/layout.js
  app/page.js
  dist/output.css
  i18n.js
  jest.config.js
  messages/en.json
  messages/tr.json
  middleware.js
  next.config.js
  package-lock.json
  package.json
  public/intro.png
  public/next.svg
  public/turkey.png
  public/united-states-of-america.png
  public/vercel.svg
  tailwind.config.js
Labels: release

#73 Amdjed belgacem/issue64
  app/Components/SearchPage/RecommendedForYou.jsx
  app/[locale]/(content-pages)/search/page.jsx
  app/api/mock/route.js
  models/Course.js
  models/User.js
  package-lock.json
  package.json
  population/populateDatabase.js
  public/howtoux.jpeg
  public/uxessentials.jpeg
  public/uxforbeginners.jpeg
  public/uxresearcher.jpeg
  script.js
  utils/database.js
Labels: feature

#69 course overview added
  app/Components/CourseDetails.jsx
  app/Components/CourseOverview.jsx
  app/Components/Icons.jsx
  app/[locale]/(content-pages)/course-preview/page.jsx
  messages/en.json
  messages/tr.json
  package-lock.json
  package.json
Labels: feature

#75 Update
  app/api/mock/route.js
  models/Achievement.js
  models/Category.js
  models/Course.js
  models/Lesson.js
  models/Transaction.js
  models/User.js
  population/populateDatabase.js
Labels: Fix

#80 Next Auth - 4Furki4/issue30
  app/Components/SideBar.jsx
  app/[locale]/(content-pages)/home/page.jsx
  app/[locale]/(content-pages)/layout.jsx
  app/[locale]/(content-pages)/search/page.jsx
  app/[locale]/get-started/page.jsx
  app/api/auth/[...nextauth]/route.js
  app/layout.js
  app/layout.jsx
  middleware.js
  models/User.js
  package-lock.json
  package.json
  script.js
Labels: feature
